### PR TITLE
Fixed mobile navbar

### LINKED ISSUE #146: Fix navbar in home page
Navbar broken when shrunken down on home page

### PR DESCRIPTION
**Pull request by Max-Changg**
- Added bg color to mobile navbar
- Clickable profile directory
- Mobile navbar now appears in home page
- Matched shape of other clickable directories
Closes #146

### CODE REVIEW

File: LootFinder/src/components/Navbar.vue [hunk 1]
```diff
@@ -108,27 +108,23 @@
 
             <!-- Display profile picture if user is logged in -->
             <template v-else>
-              <button
-                type="button"
-                class="flex items-center focus:outline-none"
-                aria-label="toggle profile dropdown"
+              <router-link
```
Comment (jonathan-herring) [inline LootFinder/src/components/Navbar.vue:111]: The profile picture does not appear on desktop view for me; looks like it's because of the negative margins. I think you can just change this router-link section to the following, and it should be good:

```
<router-link 
  to="/profile"
  class="flex items-center hover:bg-nav hover:text-white rounded-md px-3 py-2"
>
  <div
    class="w-8 h-8 overflow-hidden border-2 border-gray-400 rounded-full"
  >
    <img
      :src="user?.photoURL || 'https://via.placeholder.com/150'"
      class="object-cover w-full h-full"
      alt="avatar"
    />
  </div>
  <h3 class="mx-2 text-gray-700 lg:hidden">
    {{ user?.displayName || 'Guest' }}
  </h3>
</router-link>
```

**Review by jonathan-herring — CHANGES_REQUESTED** [review]
The profile picture doesn't appear for me in desktop view

**Review by jonathan-herring — APPROVED** [review]

**Review by michaelljiang — APPROVED** [review]
lgtm
